on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build
        run: .github/build
        env:
          TRAVIS_TAG: ${{ github.ref }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            builder/dist/*.tar.gz
            builder/dist/*.md

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: builder/dist

      - name: decrypt signing keys
        env:
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
        run: openssl aes-256-cbc -K $OPENSSL_KEY -iv $OPENSSL_IV -in .github/keys.tar.xz.enc -out .github/keys.tar.xz -d

      - name: extract signing keys
        run: tar xf .github/keys.tar.xz -C .github

      - name: import public key
        run: gpg --import .github/keys/public.key

      - name: import private key
        run: gpg --allow-secret-key-import --import .github/keys/private.key

      - name: create and upload release
        run: .github/release
        env:
          TRAVIS_REPO_SLUG: just-containers/s6-overlay
          TRAVIS_TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
